In [1]:
import numpy as np
    
x = np.array([1,2,3,4])

In [2]:
print('x = ', x)

x =  [1 2 3 4]


In [6]:
print('type = ', x.shape, type(x), x.dtype)

type =  (4,) <class 'numpy.ndarray'> int64


In [8]:
my_list = [1,2,3,4,5]

y = np.array(my_list)
print(y)

[1 2 3 4 5]


In [11]:
x1 = np.zeros((3,4))
print(x1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
x = np.arange(1, 14, 2)
print(x)

[ 1  3  5  7  9 11 13]


In [18]:
x = np.linspace(0,25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [12]:
# np array filled with ZEROs
x = np.zeros((3,4), dtype=int)

# np (4,5) array filled with 1
x = np.ones((4,5))

# fill with 5.1
x = np.full((3,4), 5.1)

# making an "identity matrix"
x = np.eye(5)

print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
# creating a "diagonal matrix"
x1 = np.diag([1,2,3,4])
print(x1)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [31]:
# accessing, deleting, and inserting elements into ndarrays

Y = np.arange(1,10).reshape(3,3)
print(y1)

w = np.delete(Y, 0, axis=0)
print("\n", w)

v = np.delete(Y, 0, axis=1)
print("\n", v)

# axis 1 is VERTICAL
# delete first coloum and last coloum
vv = np.delete(Y, [0,2], axis=1)
print("\n", vv)

# add "coloum of 5" at position 2
vvv = np.insert(Y, 1,5, axis=1)
print("\n", Y)
print("\n", vvv)

# Slicing ndarrays


[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2 3]
 [5 6]
 [8 9]]

 [[2]
 [5]
 [8]]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[1 5 2 3]
 [4 5 5 6]
 [7 5 8 9]]


In [49]:
# make a 4*5 ndarray that contain integer from 1 to 19
X = np.arange(20).reshape(4,5)
# print X
print()
print('X = \n', X)
print()

# We select all the elements that are 
# in the 2nd through 4th rows and 
# in the 3rd to 5th columns
# "ending index is always EXCLLUDED"
# "begining index is always INCLUDED"
Z = X[1:2]
print('Z = \n', Z)

X = np.arange(25).reshape(5,5)
print()
print('X = \n', X)
print()

# We print the elements in the main diagonal of X
print('z =', np.diag(X))
print()

# We print the elements above the main diagonal of X
print('y =', np.diag(X, k=2))
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[5 6 7 8 9]]

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

z = [ 0  6 12 18 24]

y = [ 2  8 14]



In [57]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1, 26).reshape(5,5)
print()
print('X = \n', X)
print()

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X % 2 != 0]
print(Y)


X = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [13]:
X = np.ones((4,4)) * np.arange(1,5)
print()
print('X = \n', X)
print()

X = np.arange(1,5)
print()
print('X = \n', X)
print(X.mean(axis=0))


X = 
 [[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


X = 
 [1 2 3 4]
2.5


In [4]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
import numpy as np
X = np.random.normal(0, 0.1, size=(1000,1000))

In [5]:
# We print X
print()
print('X = \n', X)
print()


X = 
 [[-0.05966527 -0.08353828  0.24281745 ...  0.10448772  0.25526117
  -0.02264483]
 [-0.02525613  0.21043201  0.04563132 ...  0.24854062 -0.18955852
  -0.17743965]
 [-0.08803391  0.15117895  0.06727663 ...  0.03600728 -0.00617978
   0.141393  ]
 ...
 [-0.00785499  0.07216391 -0.00457546 ... -0.1201657   0.18271899
  -0.04143641]
 [-0.13198719  0.13095543 -0.00722184 ... -0.21216722 -0.12033526
   0.08557326]
 [ 0.15861842  0.04711621  0.24927021 ...  0.09631271  0.16517971
   0.06063539]]



In [6]:
print(X.shape)

(1000, 1000)


In [8]:
print(type(X))

<class 'numpy.ndarray'>


In [10]:
print(X.mean(axis=0))

[-5.02585112e-03  2.94266974e-03  4.86974368e-05  1.91277872e-03
 -1.20330447e-03  4.46025536e-03  4.23804293e-03  4.06679671e-04
  1.23594694e-03 -4.27677491e-04 -5.82444403e-03 -9.54989366e-04
  2.23047200e-03 -1.44456228e-03  7.70977789e-04 -3.68273798e-03
 -4.19238274e-03  1.25940386e-03 -7.11875083e-03  5.38719420e-03
 -3.38778311e-03 -1.78427146e-03 -4.46643242e-03 -2.93654940e-03
  1.05519824e-03 -1.62099681e-03  3.26326574e-03  3.35456344e-03
 -5.72419366e-04 -2.36090567e-03  1.40357166e-03 -5.56143365e-04
 -4.23497633e-03 -2.68717034e-03 -4.92386388e-03  2.98307815e-03
  9.48805670e-05 -6.38819024e-03  2.72364571e-03 -4.26350391e-04
  1.41530418e-03 -2.45906771e-03 -3.91752722e-03  3.39311255e-04
  1.14914184e-03 -2.38608786e-03 -1.33538428e-03  3.75218339e-03
 -1.08710451e-03 -8.65957852e-04  4.02562492e-03 -6.36695668e-04
 -9.51089063e-04 -7.57620670e-03  4.05343797e-03 -1.04051876e-03
 -2.05178144e-03  2.77842075e-03 -9.94833963e-04 -1.72202849e-03
 -8.60393445e-05 -5.61512